# Generated by Django 4.2.7 on 2023-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dept_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptno',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='eid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
